version: 2.1

jobs:
  run:
    executor: default
    description: Echo hello world
    parameters:
      message:
        description: Message
        type: string
        default: Hello World
    steps:
      - run: echo -e "${COLOR_GREEN}<< parameters.message >>${COLOR_RESET} \U0001F44B"

executors:
  default:
    parameters:
      tag:
        description: Pick a specific circleci/node image variant.
        type: string
        default: "latest"
    docker:
      - image: circleci/node:<< parameters.tag >>
