version: 2.1

jobs:
  hello:
    executor: default
    steps:
      - run: echo "Hello World"

executors:
  default:
    parameters:
      tag:
        description: Pick a specific circleci/node image variant.
        type: string
        default: "latest"
    docker:
      - image: circleci/node:<< parameters.tag >>
